# SPDX-FileCopyrightText: 2026 SUSE LLC
# SPDX-FileContributor: CÃ©dric Bosdonnat
#
# SPDX-License-Identifier: MIT

# Default credentials, make sure to set them
credentials:
  admin:
    user: admin
    # password is the password for the product administrator user
    password:
  db:
    internal:
      user: susemanager
      # password is the password for the user of the internal database
      password:
    admin:
      user: postgres
      # password is the password for the admin user of postgresql
      password: 
    reportdb:
      user: pythia
      # password is the password for the user of the report database
      password:

global:
  # fqdn is the fully qualified name the server will answer as.
  # Changing this value renames the server and changes the server FQDN in the database, handle with care.
  # This value is required.
  fqdn:

ssl:
  country: "DE"
  province: "Bayern"
  locality: "Nurnberg"
  org: "Example"
  orgUnit: "Test"
  email: "admin@example.com"

# OpenBao specific configuration
openbao:
  # address is the URL of the openbao server, for example: "https://openbao.default.svc.cluster.local:8200"
  address:
  # caSecret can be used to point to a secret holding the root CA for the openbao in the namespace where cert-manager is installed.
  caSecret:
    name: root-ca
    key: ca.crt
  auth:
    # mountPath is appended after "/v1/auth/" in the authentication mount path
    mountPath: "kubernetes/uyuni-server-cluster"
    roleName: "uyuni-issuer-role"
  pkiPath: "pki/sign/uyuni-role"

# rootCA is the name of the secret containing the root CA certificate in the ca.crt.
# The secret needs to be in the cert-manager namespace for trust-manager to find it.
rootCA: "root-ca"

certManagerNamespace: "cert-manager"

# All the server helm chart values can be passed under this property
server-helm: {}
